"""Added option colours to db

Revision ID: 1479cb6f09ea
Revises: 450680dac4e1
Create Date: 2022-03-08 20:19:07.811314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1479cb6f09ea'
down_revision = '450680dac4e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('colour', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'colour')
    # ### end Alembic commands ###
