"""Add datetime field to listing records

Revision ID: 4d343adfa589
Revises: b52e03709370
Create Date: 2022-03-09 13:00:53.749275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d343adfa589'
down_revision = 'b52e03709370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'datetime')
    # ### end Alembic commands ###
