"""add accent colour to option

Revision ID: b52e03709370
Revises: 1479cb6f09ea
Create Date: 2022-03-08 20:26:39.643452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52e03709370'
down_revision = '1479cb6f09ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('accentColour', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'accentColour')
    # ### end Alembic commands ###
