"""Add user_odds to listings

Revision ID: dea0a9c25c47
Revises: a3a79d03291b
Create Date: 2022-03-13 17:37:24.870915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea0a9c25c47'
down_revision = 'a3a79d03291b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('user_odds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'user_odds')
    # ### end Alembic commands ###
