"""added match and history tables, fix to listing table

Revision ID: efb0a2a09fec
Revises: b57a23442f3c
Create Date: 2022-03-16 16:43:31.552430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb0a2a09fec'
down_revision = 'b57a23442f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_listing_id', sa.Integer(), nullable=True),
    sa.Column('user_matching_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_listing_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_matching_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('winning_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['winning_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('listing', sa.Column('matched', sa.Boolean(), nullable=True))
    op.drop_column('listing', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('time', sa.INTEGER(), nullable=True))
    op.drop_column('listing', 'matched')
    op.drop_table('history')
    op.drop_table('match')
    # ### end Alembic commands ###
